### ISSUE TITLE
generated code boolean as int

### ISSUE THREAD

**Issue by davidmoten** [Storyyeller/Krakatau#102]
Great product, thanks. 

I did notice that in generated code sometimes booleans were assigned to `int` which is a compile error. I assumed that `false` mapped to 0 and `true` to 1. Is this the case and can you fix the code generation?

The other compile errors that occured were methods not declaring thrown exceptions but this is straightforward to fix and didn't bother me.

**Comment by Storyyeller** [comment]
Inference of booleans is a difficult problem. I've always wanted to improve it, but it would require a huge amount of work.

As for exceptions, checked exceptions don't exist at the bytecode level, so that is not something that can be handled in general.

**Comment by davidmoten** [comment]
Thanks for the response.  Does my mapping of boolean to int seem
reasonable? False -> 0, true -> 1?

**Comment by Storyyeller** [comment]
Java compiles false to 0 and true to 1. But if (x) is compiled to if x != 0, so any nonzero value will evaluate to true. Note that this means it is possible for if (x && x != true) to hold.
