### ISSUE TITLE
exit(1) in case of error in the assembler / disassembler ?

### ISSUE THREAD

**Issue by lemonsqueeze** [Storyyeller/Krakatau#116]
Hi,

I noticed the assembler exits with status 0 even in case of error:

    $ echo garbage > foo.j
    $ assemble.py foo.j
    foo.j:1:1: error: Expected '.class' or '.version'.
    $ echo $?
    0

Maybe we could return non-zero to indicate error ? This would be useful for external tools. For example I have a Makefile rule for assembling .j files, would let make know right away when something fails.

Thanks for writing krakatau, awesome work

**Comment by Storyyeller** [comment]
Couldn't you just tell by the fact that there is output on stderr?

**Comment by lemonsqueeze** [comment]
Usually no problem, but when assembling a thousand classes it's easy to miss one...

**Comment by Storyyeller** [comment]
Should work now.
