### ISSUE TITLE
Exceptions throwing declarations

### ISSUE THREAD

**Issue by lab313ru** [Storyyeller/Krakatau#122]
For example, method throws an exception. So, in declaration it should be 'throws bla.bla.bla'. But there is no such output.

**Comment by Storyyeller** [comment]
Unfortunately, this is one of many features in Java that is impossible to decompile in general. The problem is that there are no checked exceptions at the bytecode level, so it's not clear how to handle the throws declarations required at the Java language level. One possibility is to put "throws Throwable" on every method, but that adds noise and it still doesn't compile because the compiler will complain that you aren't catching Throwable everywhere. Therefore, I decided that it was best to not try generating throws declarations at all.

**Comment by lab313ru** [comment]
Some decompilers are doing that somehow.
I think, for example enumerating all throwable exception in current method.

**Comment by Storyyeller** [comment]
They could just be using the Exceptions attribute. But Krakatau is designed to handle arbitrary bytecode, not just bytecode produced directly by Javac, so it tries to avoid relying on metadata that has no effect on execution.

**Comment by lab313ru** [comment]
Can you add some switch for that? Because if I have many methods that are throwing exceptions it becomes a hell to reconstruct the code!

**Comment by Storyyeller** [comment]
What exactly are you trying to accomplish?

**Comment by lab313ru** [comment]
Reconstruct the code with less efforts.:)

**Comment by Storyyeller** [comment]
What do you mean by "reconstruct the code"?

**Comment by lab313ru** [comment]
I have a jar file (bunch of class files), and I want to restore the code from which it was compiled. But for now I don't have that code, only jar file.

**Comment by Storyyeller** [comment]
Why do you want to do that?

**Comment by lab313ru** [comment]
One stupid mistake in my program makes me angry every time when it happens, so I want to fix it.
And I found such excellent project as Krakatau.

**Comment by Storyyeller** [comment]
Sorry, I still don't understand what you are trying to accomplish. Could you explain please?

**Comment by lab313ru** [comment]
Sure.

Look, I have a big jar file of my program, which sources I've lost. There are many methods that are throwing exceptions. But after decompilation source code doesn't have 'throws blabla' in class methods definitions.
Sure, I can add it manually in every case, but there are so many such methods that it will become a hell to fix all of that.
So, I want ask you to add this feature to decompiler: restoring exceptions info.

**Comment by skochinsky** [comment]
Does the program not work without throw declarations?

**Comment by lab313ru** [comment]
IntelliJ IDEA doesn't want to compile the source code.

**Comment by Storyyeller** [comment]
If your goal is to get back nice editable source code because you lost your source, I would recommend using a different decompiler. Of course, you'll still have to do some manual editing no matter which tool you use, and there's no way to ever recover comments or formatting.
