### ISSUE TITLE
README.TXT is out of date

### ISSUE THREAD

**Issue by Haythamamin** [Storyyeller/Krakatau#132]
README.TXT is out of date:

Usage:
python Krakatau\decompile.py [-nauto] [-path PATH] [-out OUT] [-r] [-skip]
    target

but it seems that the arguments are different. Can you please update this? Im getting unrecognized arguments error.

**Comment by Storyyeller** [comment]
What error are you getting?

**Comment by Haythamamin** [comment]
Unrecognized arguments error. I kept getting the error because the decompile.py args are different from what the package -h actually suggests. I got it to work eventually, but wanted to draw your attention to the Readme.txt instructions. Also, can you recommend a way to use decompile as API? I want to pass a list of targets to be decompiled one at a time, any suggestions?

**Comment by Storyyeller** [comment]
Could you explain which arguments you tried to pass that caused the error?

As for an API, only the command line interface is officially supported, but there's nothing stopping you from importing it as a Python module.

**Comment by Haythamamin** [comment]
in the Readme.txt file args are as follows:
python Krakatau\decompile.py [-nauto] [-path PATH] [-out OUT] [-r] [-skip] target

But in -h:
python decompile.py [-path PATH] [-out OUT] [-nauto] [-r] [-skip] [-xmagicthrow] target

I think something about the arrangement throw me off and caused " unrecognized arguments error". Also, the [-xmagicthrow] arg what is it for?

**Comment by Storyyeller** [comment]
So does that mean that everything is correct? If so, I'll go ahead and close the issue.

As for `-xmagicthrow`, it treats every non-jump instruction as being able to potentially throw, which effectively prevents Krakatau from optimizing away exception handlers based on which instructions can throw. It was added at samczsun's request, but it's not really meant for widespread usage, which is why it is undocumented.

**Comment by Haythamamin** [comment]
Yes Sir! Thank you so much for your dedication.

**Comment by Haythamamin** [comment]
Can I bug you with a question? I'm trying to log the outcome of the decompile process and I'm using subprocess to check the return. Q: how can I access the trace back to log the lib which was not found or the err in general?

Thanks
Haytham

**Comment by Storyyeller** [comment]
There isn't any easy way to do that, since going through subprocess means that you just get text back, and you'd have to parse it yourself. The best approach would be to just import Krakatau and call the code directly.

**Comment by Haythamamin** [comment]
Ok thanks.
