### ISSUE TITLE
UnicodeEncodeError ZKM on disassembling

### ISSUE THREAD

**Issue by i0xHeX** [Storyyeller/Krakatau#134]
Python 3.7.0a2
Krakatau latest zip from here.
Tried to disassemble zkm 9:
https://hastebin.com/numaluhemu.sql

It's seems problem with default Windows encoding. I googled. but found nothing useful how to fix this.
Also tried to change `151` line `script_util.py` to `with open(out, mode, encoding='utf-8')`. Disassembling good but Assembling failing with and without `encoding='utf-8'`.

**Comment by Storyyeller** [comment]
Does this happen only on Windows? Also, could you post the file you were trying to disassemble?

**Comment by i0xHeX** [comment]
I didn't tried on other platforms, but on my google searching seems unix platforms do not have similar issues.
Link to file: https://www.dropbox.com/s/8l4ucu1st615ygn/hb.class?dl=0

**Comment by i0xHeX** [comment]
Default encoding is utf8:
_>>> import sys
>>> sys.getdefaultencoding()
'utf-8'_

**Comment by i0xHeX** [comment]
Default encoding is utf8:
```
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
```

**Comment by i0xHeX** [comment]
This fixed my issue:
https://hastebin.com/enohupijas.pas

**Comment by Storyyeller** [comment]
Thanks for investigating this. I'll hopefully get to it over the weekend.

**Comment by Storyyeller** [comment]
Could you repost the file please? The link isn't working for me.

**Comment by i0xHeX** [comment]
https://ghostbin.com/paste/urx5r

**Comment by Storyyeller** [comment]
No, I mean the classfile that caused the error.

**Comment by i0xHeX** [comment]
https://www.dropbox.com/s/f3lrmwgrjhqoli3/hb%26gl.zip?dl=0

**Comment by i0xHeX** [comment]
How are things?

**Comment by Storyyeller** [comment]
Sorry, I'll try to get to it over the weekend.

**Comment by Storyyeller** [comment]
I tried disassembling the file you provided on my old Windows machine, but it disassembled without errors.

**Comment by Storyyeller** [comment]
Ok, I went ahead and pushed a fix for the issue I noticed. I can't reproduce the original error, so I'll close this for now, but if you find a way to reliably reproduce it, feel free to reply.
