### ISSUE TITLE
unnecessary super() in constructor

### ISSUE THREAD

**Issue by GraxCode** [Storyyeller/Krakatau#145]
http://prntscr.com/jecb11

**Comment by Janmm14** [comment]
Bytecode can execute before and after super call if I remember correctly.

**Comment by GraxCode** [comment]
I think that would trigger a verify error but that doesn't matter, that super call at the beginning of the constructor is redundant

**Comment by Janmm14** [comment]
Behaviour could be different. Superclass looking at variable of current class in constructor before/after init, results could differ.

**Comment by Storyyeller** [comment]
That's a good point. But I think in the case where an argument-less super() call is the first code in the function and there are no exception handlers, it can be safely removed. It shouldn't be hard to do, so I do plan to get to it eventually.

**Comment by Storyyeller** [comment]
Should be fixed now. Thanks for the report.
