### ISSUE TITLE
wrong access order

### ISSUE THREAD

**Issue by GraxCode** [Storyyeller/Krakatau#147]
Krakatau decompiles access as following:

`abstract public class`
`final public static int`

access is normally ordered as

    public
    protected
    private
    abstract
    static
    final
    transient
    volatile
    synchronized
    native
    strictfp

**Comment by Storyyeller** [comment]
The order of the flags is arbitrary, and has no effect on code behavior, so there isn't a compelling reason to prefer one order over another.
