### ISSUE TITLE
use ++ and -- for iinc

### ISSUE THREAD

**Issue by GraxCode** [Storyyeller/Krakatau#150]
iinc 0 1 is currently decompiled as 
`i0 = i0 + 1;`
but it should be decompiled as
`i0++;`

**Comment by Janmm14** [comment]
Doesn't make any difference.

**Comment by GraxCode** [comment]
But makes the code look cleaner and easier to read

**Comment by Storyyeller** [comment]
This has a very small benefit compared to the complexity of implementing it, so it's not a high priority.
