### ISSUE TITLE
Recover variable names

### ISSUE THREAD

**Issue by KOLANICH** [Storyyeller/Krakatau#167]
https://ci.appveyor.com/api/buildjobs/gtyiueue5u7joyiv/artifacts/compiler%2Fjvm%2Ftarget%2Fwindows%2Fkaitai-struct-compiler.msi (unpack it for example with lessmsi, contains a bunch of jars inside)

`io/kaitaistruct/RuntimeConfig$.java`

cfr:
```java
@Override
public RuntimeConfig apply(boolean autoRead, boolean readStoresPos, boolean opaqueTypes, CppRuntimeConfig cppConfig, String goPackage, String javaPackage, String javaFromFileClass, String dotNetNamespace, String phpNamespace, String pythonPackage) {
	return new RuntimeConfig(autoRead, readStoresPos, opaqueTypes, cppConfig, goPackage, javaPackage, javaFromFileClass, dotNetNamespace, phpNamespace, pythonPackage);
}
```

krakatau:
```java
public io.kaitai.struct.RuntimeConfig apply(boolean b, boolean b0, boolean b1, io.kaitai.struct.CppRuntimeConfig a, String s, String s0, String s1, String s2, String s3, String s4) {
	return new io.kaitai.struct.RuntimeConfig(b, b0, b1, a, s, s0, s1, s2, s3, s4);
}
```

**Comment by Storyyeller** [comment]
Krakatau is designed to handle obfuscated code, and thus it doesn't trust optional debug metadata.

**Comment by KOLANICH** [comment]
Glad to hear that. Anyway, sometimes I have to decompile nonobfuscated sources, but just not in Java, just to get the picture what is going on. So it may be useful to have this feature switcheable.

**Comment by Janmm14** [comment]
You can use another decompiler for such a case. Fernflower, CFR, Procyon (Luyten) are respecting such debug information.

**Comment by KOLANICH** [comment]
CFR, Procyon (including Luyten) and JD-GUI fail in decompiling Scala code. About Fernflower .... I haven't used it, definitely should try.
