### ISSUE TITLE
disable zip CRC checking, because java does not check it

### ISSUE THREAD

**Issue by Janmm14** [Storyyeller/Krakatau#170]
https://github.com/ItzSomebody/StopDecompilingMyJava/blob/master/decompiler-tool-bugs/Entry-010/Entry.md

**Comment by Storyyeller** [comment]
As far as I know, this can't be easily fixed in Python, but as a workaround, people can just extract the zipfile themselves before decompilation.

**Comment by Storyyeller** [comment]
FYI, the link you posted doesn't work any more. I'm guessing that this is the correct link: https://github.com/ItzSomebody/stopdecompilingmyjava/blob/master/decompiler-tool-bugs/entry-010/entry.md

**Comment by Storyyeller** [comment]
Should be fixed now.
