### ISSUE TITLE
Q: Assembler: Calls where method type is a primitive type ?

### ISSUE THREAD

**Issue by lemonsqueeze** [Storyyeller/Krakatau#171]
Hi,

Question about an unusual output i'm getting with the disassembler:
Playing around with this class: [h.class.zip](https://github.com/Storyyeller/Krakatau/files/3694451/h.class.zip) I'm getting
```
...
L10:    getfield Field androidx/d/h c [I
L13:    invokevirtual Method [I clone ()Ljava/lang/Object;
L16:    checkcast [I
```
Don't think i've come across this before,
What is this call where the method class is a primitive type ?
Looks like an int.clone() call but you can't do that in java, can you ?

**Comment by Storyyeller** [comment]
That's calling clone on an int[], that is an array of integers.
