### ISSUE TITLE
Usage of other classes

### ISSUE THREAD

**Issue by Dmunch04** [Storyyeller/Krakatau#174]
As seen in Jasmin's example of how to use classes from another file:
- https://github.com/davidar/jasmin/blob/master/examples/AnInterface.j
- https://github.com/davidar/jasmin/blob/master/examples/Implementor.j

Does it work the same way in Krakatau? Like just use the path of the file, fx. `utils/helpers/HelperClass`.

And another question real quick; how would I be able to create class fields, that is not a default data type? So it's a custom class, such as `java/lang/String`, etc.

**Comment by Janmm14** [comment]
Should work similar in krakatau.
And for fields see the documentation: https://github.com/Storyyeller/Krakatau/blob/master/Documentation/assembler.txt#L56

**Comment by Storyyeller** [comment]
Janmm14 is correct. 

Krakatau is mostly a superset of Jasmin in terms of functionality (there are some minor syntax differences compared to Jasmin).
