### ISSUE TITLE
Permission denied with disassemble.py, but not with decompile .py

### ISSUE THREAD

**Issue by juriggs** [Storyyeller/Krakatau#176]
If I use the command:

python decompile.py -skip -out temp -path C:\Users\me\Downloads\prattclasses Class1

everything works as expected

but if I use the command:

python disassemble.py -out temp -path C:\Users\me\Downloads\prattclasses Class1

I get the following error:

Traceback (most recent call last):
  File "disassemble.py", line 71, in <module>
    with zipfile.ZipFile(jar, 'r') as archive:
  File "C:\Python27\lib\zipfile.py", line 779, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 13] Permission denied: 'C:\\Users\\jriggs\\Downloads\\prattclasses'

**Comment by Storyyeller** [comment]
The disassembler doesn't take a -path argument. Check the README for details of the command line arguments.
