### ISSUE TITLE
Re-assembled class fails to load (java/lang/ClassFormatError)

### ISSUE THREAD

**Issue by minexew** [Storyyeller/Krakatau#177]
I am working with a JAR file of a commercial J2ME game. With `-roundtrip`, everything works fine.

My workflow is as follows:
```
python Krakatau/disassemble.py -out $OUT $JAR | tee disassemble.log
python Krakatau/assemble.py -out $NEWJAR -r $OUT | tee assemble.log
```
and then manually adding back non-class resources to $NEWJAR.

However, upon trying to load the MIDlet in $NEWJAR using a J2ME emulator (Sony Ericsson SDK 2.5.0.6, Sun Java 1.6.0_45 on Windows 7 32-bit), I get this error message:
```
ALERT: java/lang/ClassFormatError: Bad constant tag.
```
followed by a low-level dump of the VM stack & locals and some statistics, but no clue of the class name, or the exact "bad" tag value. Not surprisingly, the crash occurs in `com/sun/midp/midlet/MIDletState.createMIDlet`.

I would be grateful for any tips on how to debug this.

**Comment by minexew** [comment]
The bytecode is version `.version 45 3`

**Comment by Storyyeller** [comment]
Could you provide the classfile in question?

**Comment by minexew** [comment]
disassemble.py outputs a lot of these, by the way:
```
processing target b'a.class', 100/101 remaining
Nonstandard attribute b'StackMap' 197
Nonstandard attribute b'StackMap' 110
```
So far that's my only clue. But I don't see how it could be related to a constant tag.

**Comment by Storyyeller** [comment]
It's a warning that the classes contains attributes with no standard meaning, and thus that there's a risk of breaking things with non-roundtrip reassembly. I'd recommend trying to figure out what system defines the StackMap attribute and what it is used for.

**Comment by minexew** [comment]
I'm onto something. `StackMap` seems to be specific to the CLDC profile, and I think it might be enough to _preverify_ the code again after re-assembly.

**Comment by minexew** [comment]
Indeed, the problem is that the `StackMap` refers to classes by indexes in the constant pool, and these get messed up when re-assembling, even if the code itself stays the same.

Clearly, it is unrealistic to expect Krakatau to do a re-verification after reassembly (just the description of the algorithm is dozens of pages), so to protect the users I would suggest the following behavior:

- by default, encountering a `StackMap` attribute during non-roundtrip assembly raises an exception
- the user can specify an argument to drop any such attribute instead. This will not make the code magically work on a CLDC VM, but at least the VM will throw up a meaningful VerifyError
- the user can specify an argument to simply pass the attribute along, as is the current behavior. I can't imagine the use case, but who am I to judge?

If you agree, I can open a PR.

**Comment by Storyyeller** [comment]
IMO, the current behavior makes more sense. Keep in mind that Krakatau isn't specifically designed for the CLDC. It has to work with any classfile, whether they are normal Java, or CLDC, or come from Scala or whatever.

In cases where it is relevant, the user has to decide how to handle custom attributes themselves, but Krakatau does print out a warning to alert them that this is the case.

**Comment by minexew** [comment]
As far as I understood, the "StackMap" attribute is _unique_ to CLDC preverification.

The warning could be improved to at least convey the fact that an attempt at re-assembly will produce code broken in a non-obvious way. Otherwise, the claim that "this tool can roundtrip
any class through assembly and back into an equivalent class" is a bit misleading :)

**Comment by Storyyeller** [comment]
It's true for the JVM, with some caveats about reflection type APIs. But people can assign any semantics they want to non-standard attributes. You'd have the exact same issue if you were trying to modify Scala code.

**Comment by minexew** [comment]
I guess it's a matter of point of view, but why do you say non-standard? It's defined in JSR 139, Appendix 1.

**Comment by Storyyeller** [comment]
I went ahead and placed a warning in the readme about this issue.
