### ISSUE TITLE
error Traceback (most recent call last)

### ISSUE THREAD

**Issue by TechComet** [Storyyeller/Krakatau#181]
Hi,

I have error with decompile sample code
https://pastecode.io/s/1a8uv9x3

this error
https://pastecode.io/s/wrkb3asn

**Comment by Janmm14** [comment]
The problem is that the class `android.app.Activity` is not in the path you provided to Krakatau.

Krakatau requires libraries to be present.

For such simple code a decompiler like Fernflower will give you more readable code and you also do not need library jars for Fernflower.
