### ISSUE TITLE
Missing undocumented opcodes.

### ISSUE THREAD

**Issue by toxamin** [Storyyeller/Krakatau#189]
afaik they're generated by the jvm or some shit (who knows).
basically disassembly fails on this sample because of it
[BukkitPlatform.zip](https://github.com/Storyyeller/Krakatau/files/9253728/BukkitPlatform.zip)

`BREAKPOINT = 202;
LDC_QUICK = 203;
LDC_W_QUICK = 204;
LDC2_W_QUICK = 205;
GETFIELD_QUICK = 206;
PUTFIELD_QUICK = 207;
GETFIELD2_QUICK = 208;
PUTFIELD2_QUICK = 209;
GETSTATIC_QUICK = 210;
PUTSTATIC_QUICK = 211;
GETSTATIC2_QUICK = 212;
PUTSTATIC2_QUICK = 213;
INVOKEVIRTUAL_QUICK = 214;
INVOKENONVIRTUAL_QUICK = 215;
INVOKESUPER_QUICK = 216;
INVOKESTATIC_QUICK = 217;
INVOKEINTERFACE_QUICK = 218;
INVOKEVIRTUALOBJECT_QUICK = 219;
NEW_QUICK = 221;
ANEWARRAY_QUICK = 222;
MULTIANEWARRAY_QUICK = 223;
CHECKCAST_QUICK = 224;
INSTANCEOF_QUICK = 225;
INVOKEVIRTUAL_QUICK_W = 226;
GETFIELD_QUICK_W = 227;
PUTFIELD_QUICK_W = 228;
IMPDEP1 = 254;
IMPDEP2 = 255;`

**Comment by Storyyeller** [comment]
Is there any way to actually load a classfile with those opcodes? I don't think they're actually usable.

**Comment by Storyyeller** [comment]
As far as I know, the undocumented opcodes were *never* supported in classes loaded by the JVM. It's just an internal implementation detail. But there might be some secret way to make use of them.
