### ISSUE TITLE
Cannot reassemble

### ISSUE THREAD

**Issue by Valen-H** [Storyyeller/Krakatau#190]
Krakatau  Copyright (C) 2012-22  Robert Grosse
This program is provided as open source under the GNU General Public License.
See LICENSE.TXT for more details.

Processing file disassembled\module-info.j, 8305/8305 remaining
Traceback (most recent call last):
  File "E:\workspace\Python\Krakatau-master\assemble.py", line 40, in <module>
    pairs = assembleClass(target)
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\workspace\Python\Krakatau-master\assemble.py", line 16, in assembleClass
    with open(filename, 'rU') as f:
         ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'

**Comment by Storyyeller** [comment]
What version of Python are you using?

**Comment by Valen-H** [comment]
> What version of Python are you using?

The Latest from https://www.python.org/downloads/windows/

**Comment by Storyyeller** [comment]
It looks like this is a breaking change in Python 3.11. Not sure what the best way to handle that is.
https://mail.python.org/archives/list/python-dev@python.org/thread/VM3GYZDHQCXSDHZCGDA5W7ZPBYRIJPGA/

By the way, have you tried the Rust version of the assembler and dissembler? It is much faster and has some new features and bug fixes compared to the python version. https://github.com/Storyyeller/Krakatau/tree/v2

**Comment by Storyyeller** [comment]
I'm going to go ahead and close this, since this isn't an issue in Krakatau v2.
