### ISSUE TITLE
is there any grammar book/doc for krak2?

### ISSUE THREAD

**Issue by XenoAmess** [Storyyeller/Krakatau#192]
as title

**Comment by Storyyeller** [comment]
There's this, but it's a bit barebones and doesn't have the v2 changes. 

https://github.com/Storyyeller/Krakatau/blob/master/Documentation/assembler.txt

**Comment by Storyyeller** [comment]
I just wrote up a complete grammar for the assembler syntax, as well as a brief high level introduction to assembler. Please let me know if you have any questions.

https://github.com/Storyyeller/Krakatau/blob/v2/docs/assembly_specification.md
