### ISSUE TITLE
When executing the command, an error "krak2 dis --out temp"

### ISSUE THREAD

**Issue by otadoya** [Storyyeller/Krakatau#194]
This message appears. What needs to be done next?
"thread '<unnamed>' panicked at 'Unsupported output extension None', src\file_output_util.rs:30:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/main.rs:43:37"

Thank you very much in advance.

**Comment by otadoya** [comment]
Here is the complete command: "krak2 dis --out temp OpExpertiseListExc.class"

**Comment by Storyyeller** [comment]
Can you post the class please?
