### ISSUE TITLE
'rU' mode generate a backtrace in python 3.11+

### ISSUE THREAD

**Issue by martin-feaux** [Storyyeller/Krakatau#201]
Reopen of #161.

Since python 3.11, `rU` is no longer allowed.

```
python3 -W iKrakatau/ea9b62d01e53e3ab3de4731e79af2eb7b0fa3766/assemble.py -q -out a.jar -r a/
Traceback (most recent call last):
  File "Krakatau/ea9b62d01e53e3ab3de4731e79af2eb7b0fa3766/assemble.py", line 40, in <module>
    pairs = assembleClass(target)
            ^^^^^^^^^^^^^^^^^^^^^
  File "Krakatau/ea9b62d01e53e3ab3de4731e79af2eb7b0fa3766/assemble.py", line 16, in assembleClass
    with open(filename, 'rU') as f:
         ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```

**Comment by Storyyeller** [comment]
If you just need the assembler or disassembler, I'd recommend using the Rust version.

**Comment by Kreijstal** [comment]
> If you just need the assembler or disassembler, I'd recommend using the Rust version.

I mean it is an easy fix.. and some systems like cygwin dont have rust yet

**Comment by Storyyeller** [comment]
I just added a quick fix which will hopefully solve the problem, although I only have Python 3.8 installed myself so I can't check for sure.
