### ISSUE TITLE
Issue with building "cargo build --release" 

### ISSUE THREAD

**Issue by Fuzecot** [Storyyeller/Krakatau#203]
**### error: linking with `link.exe` failed: exit code: 1**
  |
  = note: "link.exe" "/NOLOGO" "C:\\Users\\USER\\AppData\\Local\\Temp\\rustc10OTRq\\symbols.o" "C:\\Users\\USER\\krakatau\\target\\release\\build\\proc-macro-error-908f6dfa7352a2e6\\build_script_build-908f6dfa7352a2e6.build_script_build.6a5ddae9a3c259e6-cgu.0.rcgu.o" "C:\\Users\\USER\\krakatau\\target\\release\\build\\proc-macro-error-908f6dfa7352a2e6\\build_script_build-908f6dfa7352a2e6.1ri0x2ha8p1c7zg1.rcgu.o" "/LIBPATH:C:\\Users\\USER\\krakatau\\target\\release\\deps" "/LIBPATH:C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\USER\\Krakatau\\target\\release\\deps\\libversion_check-6916a33f78e24b47.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-d67e7b8bedb11cdc.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-64b1a07f55304d5e.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-f120462e85f67653.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-d983e2a0a2a0c17a.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-3ef2a86080fe9062.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-eb4d69e1a344b307.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-5d40568d59362563.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-23ecb7d440e7060a.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-d852afaab40eda7f.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-20556e3a8d3a4922.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-2ad8a2d023c9ae2e.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-0731c9d2f2fdad4e.rlib" "C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-8ed27bc4ebec64d5.rlib" "kernel32.lib" "advapi32.lib" "bcrypt.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "kernel32.lib" "ws2_32.lib" "kernel32.lib" "ntdll.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\Users\\USER\\krakatau\\target\\release\\build\\proc-macro-error-908f6dfa7352a2e6\\build_script_build-908f6dfa7352a2e6.exe" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\USER\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: link: extra operand 'C:\\Users\\USER\\krakatau\\target\\release\\build\\proc-macro-error-908f6dfa7352a2e6\\build_script_build-908f6dfa7352a2e6.build_script_build.6a5ddae9a3c259e6-cgu.0.rcgu.o'
          Try 'link --help' for more information.

**and other errors all originating from the same ".O" file.**

**Comment by Storyyeller** [comment]
Are you able to build other Rust projects on your computer?

**Comment by Storyyeller** [comment]
closing due to lack of response
