### ISSUE TITLE
Jython compatibility

### ISSUE THREAD

**Issue by alexkasko** [Storyyeller/Krakatau#24]
Hi, 

I've successfully used this project with Jython 2.7b1 (you may see results in my [github project](https://github.com/alexkasko/krakatau-java)).

I applied this patch - https://gist.github.com/alexkasko/6781413 , besides jython compatibility changes (packages naming and struct creation in `assembler.py`) it also changes some `\n` to ` ` in generated source code (these changes are, of course, optional).

Thanks for the great tools!

**Comment by Storyyeller** [comment]
Closing this as I'm rewriting Krakatau in Rust.
