### ISSUE TITLE
Class not found?

### ISSUE THREAD

**Issue by IvoPereira** [Storyyeller/Krakatau#37]
Hello,

I am using the last version of Krakatau, trying to decompile a jar using the following input (i'm inside the Krakatau folder):
python decompile.py com.file.jar 

However it does produce the following results:

"Krakatau  Copyright (C) 2012-14  Robert Grosse
This program is provided as open source under the GNU General Public License.
See LICENSE.TXT for more details.

Attempting to automatically locate the standard library...
Unable to find the standard library
processing target android/UnusedStub, 4096 remaining
Loading android/UnusedStub
Loading java/lang/Object
Traceback (most recent call last):
  File "decompile.py", line 134, in <module>
    decompileClass(path, targets, args.out, args.skip)
  File "decompile.py", line 84, in decompileClass
    source = javaclass.generateAST(c, makeGraph).print_()
  File "/Users/ivopereira/Downloads/Krakatau/Krakatau/java/javaclass.py", line 69, in generateAST
    method_defs = [_getMethod(m, cb, forbidden_identifiers) for m in methods]
  File "/Users/ivopereira/Downloads/Krakatau/Krakatau/java/javaclass.py", line 39, in _getMethod
    graph = cb(method) if method.code is not None else None
  File "decompile.py", line 36, in makeGraph
    v = verifyBytecode(m.code)
  File "/Users/ivopereira/Downloads/Krakatau/Krakatau/verifier/inference_verifier.py", line 852, in verifyBytecode
    iNodes = [InstructionNode(code, offsets, key) for key in offsets[:-1]]
  File "/Users/ivopereira/Downloads/Krakatau/Krakatau/verifier/inference_verifier.py", line 147, in __init__
    self._verifyOpcodeOperands()
  File "/Users/ivopereira/Downloads/Krakatau/Krakatau/verifier/inference_verifier.py", line 234, in _verifyOpcodeOperands
    self._setProtected(False)
  File "/Users/ivopereira/Downloads/Krakatau/Krakatau/verifier/inference_verifier.py", line 344, in _setProtected
    cls = self.env.getClass(cname)
  File "/Users/ivopereira/Downloads/Krakatau/Krakatau/environment.py", line 26, in getClass
    result = self._loadClass(name, subclasses)
  File "/Users/ivopereira/Downloads/Krakatau/Krakatau/environment.py", line 60, in _loadClass
    raise ClassLoaderError('ClassNotFoundException', name)
Krakatau.error.ClassLoaderError: 
ClassNotFoundException: java/lang/Object"

Any ideas?

Thanks.

**Comment by maurice-does-software** [comment]
When I run the following

    ~/Downloads/Krakatau-master/decompile.py -path "/home/maurice/jdk1.8.0_65/jre/lib/rt.jar" ./path/to/my/classes/

I still get the "Unable to find the standard library" error. Do I have the syntax wrong somewhere? I assume if it were actually a different library missing at this point, it wouldn't still say "the standard library", right?

**Comment by maurice-does-software** [comment]
Ok. I noticed the readme says "Note that the decompiler does not currently support Java 8[...]" so I installed 7 via apt, in the standard location, but am still getting the same error.

**Comment by Storyyeller** [comment]
Which class did it say wasn't found? It's probably needs another library.

Each time it says a class is missing, just add the jar with that class to
the path.

**Comment by PallaviKumariJha** [comment]
Hi,

I have a .jar. I wish to deobfuscate it and run it in eclipse. Krakatau seems very promising for this. While running it I am also getting the same message on my console. I run the command as following:

C:\Python27> .\python.exe <pathTo\decompile.py> -path "C:\Program Files\Java\jr
1.8.0_144\lib\rt.jar" -out <pathToOutputFolder> -r -skip <pathToTheJar>

Message on Powershell is as following:
***********************************************************************************************************
Krakatau  Copyright (C) 2012-17  Robert Grosse
This program is provided as open source under the GNU General Public License.
See LICENSE.TXT for more details.

Attempting to automatically locate the standard library...
Unable to find the standard library
0 extra classes loaded
*************************************************************************************************************
Also, as you can see it does not tell me which are the standard libraries it needs. I am unable to figure out what is going wrong. Kindly help me here.

Note: I would also like to know how did you figure out rt.jar was to be included in the path? (from the first question asked here by IvoPereira)

**Comment by Storyyeller** [comment]
If there is a class missing, and you don't pass -skip, it will tell you the name of the class. You can usually figure out which dependency you need by googling the name of the class. I agree that it's a terrible system (I'm annoyed by it as much as you), but I'm not sure how to improve it, as redesigning Krakatau to not require class hierarchy information is a nonstarter.
