### ISSUE TITLE
Lambda assembling

### ISSUE THREAD

**Issue by lisu188** [Storyyeller/Krakatau#47]
When i disassembled and assembled again following class:

 public class Main {
    private static final List<String> ARR = Arrays.asList("1", "2", "3");

    public static void main(String[] args) {
        ARR.forEach(x -> System.out.println(x));
    }
}

i got an exception:

Krakatau\constant_pool.py", line 206, in bytes
    t = name2Type[name]
KeyError: 'Methodtype'

and when i "iffed" that place to change key to 'MethodType' it has successfully compiled

**Comment by Storyyeller** [comment]
Well Java 8 isn't officially supported yet (mainly because I don't have the time and it's not a priority). But if the change required is that simple, I'll go ahead and look into it.

**Comment by Storyyeller** [comment]
Should be fixed now.
