### ISSUE TITLE
assemble.py Error: ImportError: No module named ply

### ISSUE THREAD

**Issue by Djamana** [Storyyeller/Krakatau#51]
Okay I fixed it. 
But well please mention it in the readme + 2-3 lines for python newbies like me.
Who really starts likes starts to like it because of it's philosophy:  'Batteries included' :D
OKAY:
1.Download ply (which stands for 'PYthon Lex & yacc')
**https://pypi.python.org/pypi/ply**
2. install it with the command:
**setup.py install**

That's it no more errors on the sourcecode line: 
    from ply import lex

**Comment by Storyyeller** [comment]
The Readme does say that the assembler requires PLY. There are various ways to set it up, so it doesn't make much sense to me to include instructions.
