### ISSUE TITLE
assembler error with .const Long

### ISSUE THREAD

**Issue by skochinsky** [Storyyeller/Krakatau#53]
I think current code is not completely ready to handle two-slot consts (long/double). See
[this sample](https://github.com/Storyyeller/Krakatau/files/46581/vasco_1_1.txt). Stack trace:

    Traceback (most recent call last):
      File "Krakatau\assemble.py", line 47, in <module>
        pairs = assembleClass(log, target, args.g, args.jas, args.d)
      File "Krakatau\assemble.py", line 23, in assembleClass
        return parse_trees and [assembler.assemble(tree, makeLineNumbers, jasmode, basename) for tree in parse_trees]
      File "Krakatau\Krakatau\assembler\assembler.py", line 528, in assemble
        addLdcRefs(top_d['method'], pool)
      File "Krakatau\Krakatau\assembler\assembler.py", line 441, in addLdcRefs
        assert(not slots)
    AssertionError

**Comment by skochinsky** [comment]
BTW, I tried using `ldc NNL` and it didn't work either:

    Syntax error at line 8571: unexpected token u'-9223372036854775808L'
    Expected: INT_LITERAL, CPINDEX, STRING_LITERAL, FLOAT_LITERAL
    Found: LONG_LITERAL

**Comment by Storyyeller** [comment]
I'm working on a complete rewrite of the assembler, so I'm not going to bother looking into this. I'll just make sure that it works in the new version. Thanks for reporting it anyway.
