### ISSUE TITLE
prevents disassemble.py from writing out debug info

### ISSUE THREAD

**Issue by carlitosLMO** [Storyyeller/Krakatau#57]
How to prevents disassemble.py from writing out debug info like:
   -    L1: ...
   -   .linenumbertable ... .end linenumbertable
   -   .localvariabletable ... .end localvariabletable

Apktool has "--no-debug-info" option.
There is any similar option for disassemble.py?
tks

**Comment by Storyyeller** [comment]
Not currently, but I can easily add one.

What do you think about having an option --hideattrs=... that you can blacklist attributes. Then you can do something like --hideattrs=LineNumberTable,LocalVariableTable,LocalVariableTypeTable

**Comment by Storyyeller** [comment]
Alternatively, what do you think about an option called -codeonly that ignores all attributes besides Code, ConstantValue, and BootstrapMethodsTable?

**Comment by carlitosLMO** [comment]
an option called -codeonly will be great!
It would be easier to edit the file and then re-compile with "assemble.py"

**Comment by Storyyeller** [comment]
If you're going to reassemble, you'll want to include the other attributes though. At least StackMapTable, and the inner class and annotation stuff.

**Comment by carlitosLMO** [comment]
Would it be possible to remove these parts:
.stack stack_1 ...
.stack full ... .end stack
L1: ...
.linenumbertable ... .end linenumbertable
.localvariabletable ... .end localvariabletable

and then re-compile?

**Comment by Storyyeller** [comment]
Yes, but if you remove the stackmap from a 51.0+ classfile, it won't run any more.

**Comment by Storyyeller** [comment]
Did you ever make up your mind about the desired behavior?

**Comment by Storyyeller** [comment]
Closing due to lack of response.

**Comment by Kreijstal** [comment]
you could just strip the debug info from the class at a later time with another tool no?
