### ISSUE TITLE
JSR Confusion

### ISSUE THREAD

**Issue by samczsun** [Storyyeller/Krakatau#65]
So if you're having a boring day and you want something to work on, here's a fun edge case to fix.

```java
redacted
```

Other decompilers will decompile straight to

```java
   public static void main(String[] var0) {
      System.out.println("Nothing to see here, Officer");
   }
```

However, Krakatau trips up at blockmaker.py on line 691

```
node = self.iNodeD[key]
KeyError: 19
```

The KeyError error might be an easier fix than the potential jsr confusion

**Comment by Storyyeller** [comment]
Should be fixed now. 

As far as jsr confusion goes, Krakatau already handles this control flow correctly and always has. Unlike most decompilers, I tried to get these things right.

**Comment by samczsun** [comment]
```java
.method public static main : ([Ljava/lang/String;)V 
    .code stack 10 locals 10
        jsr Ltest1
        getstatic java/lang/System out Ljava/io/PrintStream;
        ldc "Insert CryptoLocker code here..."
        invokevirtual java/io/PrintStream println (Ljava/lang/String;)V
        return
Ljsr2:
        iconst_0
        iconst_1
        invokestatic Method java/lang/Math min (II)I
        ifeq L1
        pop
        goto Ltest1
L1:
        swap
        astore_1
        ret 1
Ltest1:
        jsr Ljsr2
        getstatic java/lang/System out Ljava/io/PrintStream;
        ldc "Nothing to see here, Officer"
        invokevirtual java/io/PrintStream println (Ljava/lang/String;)V
        return
    .end code 
.end method
```

Thought I'd post here instead of opening a new issue (unless you prefer new issues in which case let me know).

This one causes an AssertionError at
```assert(block.predecessors == [(jsrblock, False)])```

**Comment by Storyyeller** [comment]
I don't think that's valid bytecode

Are you able to run it? When I try to run it, I get an error
Exception in thread "main" java.lang.VerifyError: Bad instruction: a8
Exception Details:
  Location:
    Confusion.main([Ljava/lang/String;)V @0: jsr
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: a800 1cb2 0008 1201 b600 09b1 0304 b800
    0x0000010: 0a99 0007 57a7 0007 5f4c a901 a8ff f0b2
    0x0000020: 0008 1202 b600 09b1                    

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)

**Comment by Storyyeller** [comment]
Interesting. I think I forgot about the possibility of normal jumps to the beginning of a subprocedure.
