### ISSUE TITLE
Renaming during decompilation/disassembly

### ISSUE THREAD

**Issue by crashish** [Storyyeller/Krakatau#66]
I've been considering methods to systematically rename classes/methods/etc as a way to reduce the impact of certain obfuscation schemes, and have been hoping to leverage Krakatau in this. I'm digging through the code to understand where I'll need to make changes to accomplish this but was wondering if you might have any input or suggestions.

**Comment by Storyyeller** [comment]
I've experimented with this in the past, but there isn't any official way to do it. I'd recommend starting with the experimental_deobfuscation branch, which IIRC includes my old renaming code.

**Comment by Janmm14** [comment]
Use for example https://github.com/md-5/SpecialSource for renaming manually.

**Comment by samczsun** [comment]
It doesn't make much sense to package a Java application into a Python program
