### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by ShootingMilk** [Storyyeller/Krakatau#68]
Does this not work with Windows 10?

**Comment by ShootingMilk** [comment]
![image](https://cloud.githubusercontent.com/assets/13566694/13452214/de69362a-e080-11e5-83e9-44c2d89ba48b.png)

**Comment by skochinsky** [comment]
What exactly are you trying to run? Krakatau is Python code, and Python most definitely runs on Windows 10.
