### ISSUE TITLE
Maximum recursion depth

### ISSUE THREAD

**Issue by samczsun** [Storyyeller/Krakatau#80]
This was a fun one to find. Likely system-independent but here's the assembly file I used

https://cloud.samczsun.com/f/25ad7e6277/

In javamethod.py
```
expr.params = map(simplify, expr.params)
```

**Comment by Storyyeller** [comment]
I guess I should add the limit on expression nesting back in? It's a bit of a dilemma, because in most cases, inlining expressions makes the resulting code more readable.

**Comment by samczsun** [comment]
Yeah, you could increase the stack size but that might lead to DoS vulns. Best solution might be to just have a counter
