### ISSUE TITLE
Dissaseble by class not working

### ISSUE THREAD

**Issue by drecker** [Storyyeller/Krakatau#82]
Hi everyone,

when I use **decompile**: `python ~/Krakatau/decompile.py -path myjar.jar a.a` it nicely decompiles the a.a class.

But when i do **disassemble**: `python ~/Krakatau/disassemble.py -path myjar.jar a.a` it ends with error `KeyError: "There is no item named 'a' in the archive"`

**Comment by Storyyeller** [comment]
That's because the disassembler works on files, not classes. You need to specify a.a.class
