### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getSingleTType'

### ISSUE THREAD

**Issue by samczsun** [Storyyeller/Krakatau#87]
```java
.method public static main : ([Ljava/lang/String;)V 
    .code stack 1024 locals 10
	.catch [0] from Lb to Lc using Ld
Lb:
        aconst_null
        athrow
Lc:
Ld:
        athrow
        return
    .end code 
.end method 
```

Looks like mishandling of finally blocks

**Comment by Storyyeller** [comment]
For the record, Krakatau doesn't believe in finally blocks. .catch [0] is handled exactly the same as .catch java/lang/Throwable

**Comment by samczsun** [comment]
I've managed to reproduce this without using finally at all, but decided to hold back the second issue unless it wasn't fixed by this. If you would like I can post the assembly for that tomorrow

**Comment by Storyyeller** [comment]
bring it on :)

**Comment by Storyyeller** [comment]
In case you were wondering, the problem is that I incorrectly updated simplifyThrows() when I introduced extended basic blocks. Instead of checking the input to the throw instruction for nullness, I checked the output of the ephi, but the later is always non-null, making the check useless.

**Comment by samczsun** [comment]
> bring it on :)

I brought it but you've patched it :(
