### ISSUE TITLE
Request: automatically upgrade ldc to ldc_w when necessary

### ISSUE THREAD

**Issue by toddATavail** [Storyyeller/Krakatau#90]
It would be very nice if the assembler would automatically promote an ldc instruction to an ldc_w instruction when necessary, i.e., when the constant reference no longer fits in a byte, rather than producing an error that the wrong instruction has been specified.

I appreciate that this would not preserve low-level fidelity, but since it is extremely inconvenient to determine how many constants are being used in generated code, it seems an important feature. One of the very nice things about Krakatau is that I can generate JVM instructions without having to manage a constant pool in my code generator. But if Krakatau lacks niceties like the ability to promote an instruction to a corresponding wide form when appropriate, then I would have to manage a constant pool after all. And the more management code I have to write, the more expensive becomes the proposition of using the assembler. Features like the one that I am requesting are one of the reasons why textual assemblers were invented in the first place — to abstract away the incredibly low-level details.

As a workaround, I am simply emitting ldc_w now instead of ldc, always. But it would be nice to just emit ldc (always) and let the assembler adjust as appropriate.

**Comment by Storyyeller** [comment]
What is wrong with just always using ldc_w?

**Comment by Storyyeller** [comment]
On a side note, such a feature would raise a whole bunch of thorny issues. For example, how would it decide which instructions to widen/shorten and which to leave as is? If you don't care, then it means that the feature is basically useless in the first place. You could achieve the same effect in seconds by just doing a search/replace 'ldc ' -> 'ldc_w '. If you do care, then you'd probably want a way to specify which instructions you want to be wide and which you want to be short, in case you're back to the status quo.
