### ISSUE TITLE
issues decompiling Krakatau-assembled code

### ISSUE THREAD

**Issue by skochinsky** [Storyyeller/Krakatau#92]
So I'm trying to decompile the Java code use by ME using my JEFF to java asm dumper. However, I keep having troubles. Here's the repro steps:
1) assemble the core file: https://gist.github.com/skochinsky/4ccd419043d33bd4d6bed1880d59f556
2) zip up generated clases into a jar (BTW, would be cool if assembler did that automatically)
3) assemble the OATH applet code: https://gist.github.com/skochinsky/d19d4d69ae3c354406231701c276b304
2) zip the classes up again
3) try decompiling it: 
decompile.py" -path jeff-core10.jar  -nauto  o100.jar

4) get an assert or exception, e.g.:

```
Traceback (most recent call last):
  File "C:\Work\me\_me new 6\Krakatau-master2\decompile.py", line 155, in <module>
    decompileClass(path, targets, args.out, args.skip, magic_throw=args.xmagicthrow)
  File "C:\Work\me\_me new 6\Krakatau-master2\decompile.py", line 100, in decompileClass
    source = printer.visit(javaclass.generateAST(c, makeGraphCB, skip_errors, add_throws=add_throws))
  File "C:\Work\me\_me new 6\Krakatau-master2\Krakatau\java\javaclass.py", line 67, in generateAST
    method_defs = [_getMethod(m, cb, forbidden_identifiers, skip_errors) for m in methods]
  File "C:\Work\me\_me new 6\Krakatau-master2\Krakatau\java\javaclass.py", line 37, in _getMethod
    graph = cb(method) if method.code is not None else None
  File "C:\Work\me\_me new 6\Krakatau-master2\decompile.py", line 45, in makeGraph
    v = verifyBytecode(m.code)
  File "C:\Work\me\_me new 6\Krakatau-master2\Krakatau\verifier\inference_verifier.py", line 497, in verifyBytecode
    start = iNodes[0]
IndexError: list index out of range

```
or (with an older revision):

```
Traceback (most recent call last):
  File "C:\Work\me\_me new 6\Krakatau-master\decompile.py", line 148, in <module>
    decompileClass(path, targets, args.out, plugins, args.skip)
  File "C:\Work\me\_me new 6\Krakatau-master\decompile.py", line 88, in decompileClass
    c = e.getClass(target)
  File "C:\Work\me\_me new 6\Krakatau-master\Krakatau\environment.py", line 28, in getClass
    result.loadElements()
  File "C:\Work\me\_me new 6\Krakatau-master\Krakatau\classfile.py", line 114, in loadElements
    self.methods = [method.Method(m, self, keepRaw) for m in self.methods_raw]
  File "C:\Work\me\_me new 6\Krakatau-master\Krakatau\method.py", line 94, in __init__
    self._loadCode(keepRaw)
  File "C:\Work\me\_me new 6\Krakatau-master\Krakatau\method.py", line 112, in _loadCode
    assert(len(code_attrs) == 1)
AssertionError

```

Now, It's possible that I'm doing something wrong in generated asm again, but I'm not sure what it could be...

**Comment by Storyyeller** [comment]
The second error message you posted implies that you have a non-native non-abstract method with no code attribute. Can you check whether that is the case?

If not, please post the jar you are trying to decompile so I can take a look.

As for jar output from the assembler, it will automatically do that already if you pass an output path that ends in .jar or .zip. This is also documented in the README. Do you have suggestions for how I can make it clearer?

**Comment by skochinsky** [comment]
Thanks, apparently the jeff file is missing the abstract flag for empty methods. I'll probably have to add a workaround. Thanks for the hint on the out path! I would maybe clarify it in the commandline help, e.g:

` -out OUT    Path to generate files in (directory or jar/zip)`

**Comment by Storyyeller** [comment]
Note that including those .limit directives implies the creation of an (empty) code attribute. So you should remove those too if the methods aren't supposed to have code.

**Comment by skochinsky** [comment]
In fact, it looks like they do have code but it's not dumped for some reason. In any case, looks like the bug is on my side, however, maybe a warning for empty non-abstract methods at assembly time  would be useful, or at least a clearer error message instead of a silent assert.

**Comment by Storyyeller** [comment]
The assembler deliberately supports creation of invalid classfiles, partly to simplify things and partly because invalid classfiles can be useful for testing Java tools. I'm not sure how much sense a warning would make. Is this a common problem?

**Comment by skochinsky** [comment]
sorry for the noise, but I still can't get it working :( I updated my script to produce the new syntax and I'm not seeing any empty methods anymore (I *think*) but I'm still getting the assert. Any idea what's wrong? updated source: https://gist.github.com/skochinsky/4ccd419043d33bd4d6bed1880d59f556 (just assemble it and try decompiling the jar).

**Comment by skochinsky** [comment]
Oh sorry, there was an assembler error that got scrolled off the screen... looks like it's not liking negative constants in lookupswitch:

```
         lookupswitch
                    -2: LABEL_016A
                    -1: LABEL_0160
                    default: LABEL_0178

jeff_core10.j:12987:21: error: Invalid token. Did you mean to use quotes?
                    -2: LABEL_016A
                    ^~~
```

Is this an assembler issue or I actually need to convert them to unsigned values?

**Comment by skochinsky** [comment]
hm, unsigneds do not work:

```
jeff_core10.j:12987:20: error: Value must be in range -2147483648 <= x < 2147483648
                   0xFFFFFFFE: LABEL_016A
                   ^~~~~~~~~~             

```

**Comment by skochinsky** [comment]
Okay, updated source once more: https://gist.github.com/skochinsky/4ccd419043d33bd4d6bed1880d59f556/02bab26278c5c9a5b4b0ad923831dc02d0b52e5a
It now assembles and disassembles without errors, but still asserts when decompiling :(

**Comment by Storyyeller** [comment]
You need to put a space between the int and the colon for the switch keys.

Also, what is the assert error? Anyway, I'll be away from my computer for the next week, but if you haven't figured it out by then, I'll take a look.

**Comment by skochinsky** [comment]
here's the backtrace:

```
Traceback (most recent call last):
  File "C:\Work\me\_me new 6\Krakatau-master\decompile.py", line 148, in <module>
    decompileClass(path, targets, args.out, plugins, args.skip)
  File "C:\Work\me\_me new 6\Krakatau-master\decompile.py", line 88, in decompileClass
    c = e.getClass(target)
  File "C:\Work\me\_me new 6\Krakatau-master\Krakatau\environment.py", line 28, in getClass
    result.loadElements()
  File "C:\Work\me\_me new 6\Krakatau-master\Krakatau\classfile.py", line 114, in loadElements
    self.methods = [method.Method(m, self, keepRaw) for m in self.methods_raw]
  File "C:\Work\me\_me new 6\Krakatau-master\Krakatau\method.py", line 94, in __init__
    self._loadCode(keepRaw)
  File "C:\Work\me\_me new 6\Krakatau-master\Krakatau\method.py", line 112, in _loadCode
    assert(len(code_attrs) == 1)
AssertionError

```

**Comment by Storyyeller** [comment]
That means you have 0 (or possibly 2+) code attributes in one of your methods.

**Comment by skochinsky** [comment]
Was caused by  some debugging code... sorry for all the noise.
