### ISSUE TITLE
test + 1 has different bytecode than test++?

### ISSUE THREAD

**Issue by Manouchehri** [Storyyeller/Krakatau#97]
Running across an odd issue where it appears that Java doesn't compile `test + 1` as the same as `test++`.

## Original functions

```java
public class VotingMachine {
    private int demoVotes, repubVotes;

    public void voteDemo() {
        this.demoVotes++;
    }
    public void voteRepub() {
        this.repubVotes++;
    }
    // Other functions removed to save space.
}
```

## Krakatau output

```java
public class VotingMachine {
    private int demoVotes;
    private int repubVotes;
    
    public void voteDemo() {
        this.demoVotes = this.demoVotes + 1;
    }
    public void voteRepub() {
        this.repubVotes = this.repubVotes + 1;
    }
    // Other functions removed to save space.
}
```

![combined_votedemo vs votedemo](https://cloud.githubusercontent.com/assets/7232674/16643573/dd9fb8f6-43e3-11e6-82ca-5c2983cc25b3.png)

![combined_voterepub vs voterepub](https://cloud.githubusercontent.com/assets/7232674/16643093/567eb574-43df-11e6-8115-812305b2e801.png)

CFR, Fernflower and Procyon all decompile to `++this.demoVotes;` and `++this.repubVotes;`.

**Comment by Storyyeller** [comment]
How is this a bug? You obviously can't expect to get the exact same bytecode back after decompiling and recompiling. You're lucky when it compiles at all.

**Comment by Manouchehri** [comment]
@Storyyeller I think you misread what I wrote. Let me write it out in a table to be a bit more clear.

1. `aload_0; dup` == `test++`
2. `aload_0; aload_0` == `test = test + 1`
3. `aload_0; dup` != `test = test + 1`
4. `aload_0; aload_0` != `test++`

Krakatau is incorrectly decompiling `aload_0; dup` as `test = test + 1` instead of `test++`.

**Comment by Manouchehri** [comment]
Because CFR, Fernflower and Procyon all correctly decompile `aload_0; dup` as `test++`, that implies to me that it's a Krakatau bug.

**Comment by Storyyeller** [comment]
It's not a bug because the expressions are equivalent.
