### ISSUE TITLE
FeatureRequest: Multithread support

### ISSUE THREAD

**Issue by Djamana** [Storyyeller/Krakatau#98]
I see that decompile.py is just using one cpu core / thread.
Would be nice to see it using the full power of my cpu.
So can ya make it to use a threads to decompile a class file and then
run multiple thread/instances of that at once.

**Comment by Storyyeller** [comment]
You mean multiple processes? There's not much point to trying to add threading unless you happen to be using pypy-stm.

**Comment by Djamana** [comment]
Hmm I don't meant multiple processes (Would be a little overbloated but this may work also).
 Just a single processes that runs 2 or more threads in parallel that will decompile each one a different class file.
Well pypy-stm doc sound nice:
> The benefit is that the resulting pypy-stm can execute multiple threads of Python code in parallel. Programs running two threads or more in parallel should ideally run faster than in a regular PyPy (either now, or soon as bugs are fixed).
http://doc.pypy.org/en/latest/stm.html

**Comment by Storyyeller** [comment]
The problem is that this is basically impossible in Python. You're welcome to try though.
